services:
  postgres:
    image: postgres:16
    container_name: fanticbet-db
    environment:
      POSTGRES_USER: fanticbet
      POSTGRES_PASSWORD: fanticbet
      POSTGRES_DB: fanticbet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
